  
PROMPT Creating Primary Key on 'ETUDIANT'
ALTER TABLE ETUDIANT
 ADD (CONSTRAINT ETU_PK PRIMARY KEY 
  (NO_ETUDIANT))
/

PROMPT Creating Primary Key on 'ENSEIGNANT'
ALTER TABLE ENSEIGNANT
 ADD (CONSTRAINT ENS_PK PRIMARY KEY 
  (NO_ENSEIGNANT))
/

PROMPT Creating Primary Key on 'PROMOTION'
ALTER TABLE PROMOTION
 ADD (CONSTRAINT PRO_PK PRIMARY KEY 
  (ANNEE_UNIVERSITAIRE
  ,CODE_FORMATION))
/

PROMPT Creating Primary Key on 'ELEMENT_CONSTITUTIF'
ALTER TABLE ELEMENT_CONSTITUTIF
 ADD (CONSTRAINT EC_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE
  ,CODE_EC))
/


PROMPT Creating Primary Key on 'UNITE_ENSEIGNEMENT'
ALTER TABLE UNITE_ENSEIGNEMENT
 ADD (CONSTRAINT UE_PK PRIMARY KEY 
  (CODE_FORMATION
  ,CODE_UE))
/

PROMPT Creating Primary Key on 'FORMATION'
ALTER TABLE FORMATION
 ADD (CONSTRAINT FRM_PK PRIMARY KEY 
  (CODE_FORMATION))
/

PROMPT Creating Primary Key on 'EVALUATION'
ALTER TABLE EVALUATION
 ADD (CONSTRAINT EVE_PK PRIMARY KEY 
  (ID_EVALUATION))
/

PROMPT Creating Primary Key on 'QUESTION_EVALUATION'
ALTER TABLE QUESTION_EVALUATION
 ADD (CONSTRAINT QEV_PK PRIMARY KEY 
  (ID_QUESTION_EVALUATION))
/

PROMPT Creating Primary Key on 'RUBRIQUE_QUESTION'
ALTER TABLE RUBRIQUE_QUESTION
 ADD (CONSTRAINT RBQ_PK PRIMARY KEY 
  (ID_RUBRIQUE
  ,ID_QUESTION))
/

PROMPT Creating Primary Key on 'RUBRIQUE'
ALTER TABLE RUBRIQUE
 ADD (CONSTRAINT RUB_PK PRIMARY KEY 
  (ID_RUBRIQUE))
/

PROMPT Creating Primary Key on 'RUBRIQUE_EVALUATION'
ALTER TABLE RUBRIQUE_EVALUATION
 ADD (CONSTRAINT REV_PK PRIMARY KEY 
  (ID_RUBRIQUE_EVALUATION))
/

PROMPT Creating Primary Key on 'DROIT'
ALTER TABLE DROIT
 ADD (CONSTRAINT DRT_PK PRIMARY KEY 
  (ID_EVALUATION
  ,NO_ENSEIGNANT))
/

PROMPT Creating Primary Key on 'QUALIFICATIF'
ALTER TABLE QUALIFICATIF
 ADD (CONSTRAINT QUA_PK PRIMARY KEY 
  (ID_QUALIFICATIF))
/

PROMPT Creating Primary Key on 'QUESTION'
ALTER TABLE QUESTION
 ADD (CONSTRAINT QUE_PK PRIMARY KEY 
  (ID_QUESTION))
/

PROMPT Creating Primary Key on 'REPONSE_QUESTION'
ALTER TABLE REPONSE_QUESTION
 ADD (CONSTRAINT RPQ_PK PRIMARY KEY 
  (ID_REPONSE_EVALUATION
  ,ID_QUESTION_EVALUATION))
/

PROMPT Creating Primary Key on 'REPONSE_EVALUATION'
ALTER TABLE REPONSE_EVALUATION
 ADD (CONSTRAINT RPE_PK PRIMARY KEY 
  (ID_REPONSE_EVALUATION))
/
